# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: b2c2ebee9aae33c22d2b23028cb415e35b92de9c2b498e027708cc82c3b46cc5f45afaac9958dbd279c634ae2f09f773724ccdadfcdb95c3fb80c2ed290dfff1

test:
  secret_key_base: 4c76859904a9b824c44d49f3ca611d1ee348b0bee6ea97e1cbcf58ad79288bf29a1041b152d07a9afbf0ae83be621c651a22cd29a799455fd55d5d58d93edfd8

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
